import 'package:flutter/foundation.dart';
import 'package:shared/shared.dart';

class CartProvider extends ChangeNotifier {
  final List<OrderItem> _items = [];
  String? _selectedRestaurantId;
  DeliveryAddress? _deliveryAddress;
  String? _specialInstructions;

  List<OrderItem> get items => List.unmodifiable(_items);
  String? get selectedRestaurantId => _selectedRestaurantId;
  DeliveryAddress? get deliveryAddress => _deliveryAddress;
  String? get specialInstructions => _specialInstructions;
  
  int get itemCount => _items.length;
  
  double get subtotal {
    return _items.fold(0.0, (sum, item) => sum + item.totalPrice);
  }
  
  double get deliveryFee => 0.0; // TODO: Get from restaurant
  
  double get tax => subtotal * 0.1; // 10% tax
  
  double get discount => 0.0; // TODO: Implement discounts
  
  double get total => subtotal + deliveryFee + tax - discount;

  bool get isEmpty => _items.isEmpty;

  bool canAddProduct(String restaurantId) {
    if (_selectedRestaurantId == null) return true;
    return _selectedRestaurantId == restaurantId;
  }

  void addItem(OrderItem item) {
    // Check if item already exists with same variant and addons
    final existingIndex = _items.indexWhere((existingItem) =>
      existingItem.productId == item.productId &&
      _compareVariants(existingItem.selectedVariant, item.selectedVariant) &&
      _compareAddons(existingItem.selectedAddons, item.selectedAddons),
    );

    if (existingIndex != -1) {
      // Update quantity
      final existingItem = _items[existingIndex];
      _items[existingIndex] = OrderItem(
        productId: existingItem.productId,
        productName: existingItem.productName,
        productImageUrl: existingItem.productImageUrl,
        quantity: existingItem.quantity + item.quantity,
        unitPrice: existingItem.unitPrice,
        selectedVariant: existingItem.selectedVariant,
        selectedAddons: existingItem.selectedAddons,
        specialInstructions: existingItem.specialInstructions,
      );
    } else {
      _items.add(item);
    }

    notifyListeners();
  }

  void removeItem(int index) {
    if (index >= 0 && index < _items.length) {
      _items.removeAt(index);
      
      if (_items.isEmpty) {
        _selectedRestaurantId = null;
        _deliveryAddress = null;
        _specialInstructions = null;
      }
      
      notifyListeners();
    }
  }

  void updateQuantity(int index, int quantity) {
    if (index >= 0 && index < _items.length && quantity > 0) {
      final item = _items[index];
      _items[index] = OrderItem(
        productId: item.productId,
        productName: item.productName,
        productImageUrl: item.productImageUrl,
        quantity: quantity,
        unitPrice: item.unitPrice,
        selectedVariant: item.selectedVariant,
        selectedAddons: item.selectedAddons,
        specialInstructions: item.specialInstructions,
      );
      notifyListeners();
    }
  }

  void setRestaurant(String restaurantId) {
    if (_selectedRestaurantId != restaurantId) {
      _selectedRestaurantId = restaurantId;
      // Clear cart if changing restaurant
      if (_selectedRestaurantId != null && !_items.isEmpty) {
        _items.clear();
      }
      notifyListeners();
    }
  }

  void setDeliveryAddress(DeliveryAddress address) {
    _deliveryAddress = address;
    notifyListeners();
  }

  void setSpecialInstructions(String? instructions) {
    _specialInstructions = instructions;
    notifyListeners();
  }

  void clearCart() {
    _items.clear();
    _selectedRestaurantId = null;
    _deliveryAddress = null;
    _specialInstructions = null;
    notifyListeners();
  }

  Order createOrder(String customerId, PaymentMethod paymentMethod) {
    if (_items.isEmpty || _deliveryAddress == null) {
      throw Exception('Cart is empty or no delivery address');
    }

    return Order(
      id: '', // Will be generated by Firestore
      customerId: customerId,
      restaurantId: _selectedRestaurantId!,
      items: List.from(_items),
      deliveryAddress: _deliveryAddress!,
      status: OrderStatus.pending,
      paymentMethod: paymentMethod,
      subtotal: subtotal,
      deliveryFee: deliveryFee,
      tax: tax,
      discount: discount,
      total: total,
      specialInstructions: _specialInstructions,
      createdAt: DateTime.now(),
    );
  }

  bool _compareVariants(ProductVariant? a, ProductVariant? b) {
    if (a == null && b == null) return true;
    if (a == null || b == null) return false;
    return a.name == b.name && a.price == b.price;
  }

  bool _compareAddons(List<ProductAddon>? a, List<ProductAddon>? b) {
    if (a == null && b == null) return true;
    if (a == null || b == null) return false;
    if (a.length != b.length) return false;
    
    for (int i = 0; i < a.length; i++) {
      if (a[i].name != b[i].name || a[i].price != b[i].price) {
        return false;
      }
    }
    
    return true;
  }
}
